- name: Demo on template
  hosts: localhost
  tasks:
    - name: Copy File
      ansible.builtin.copy:
        src: hello.txt
        dest: /tmp/h1.txt

    - name: Template file
      ansible.builtin.template:
        src: hello.txt
        dest: /tmp/h2.txt

# ansible-playbook template.yml -e name=John
# output of cat /tmp/h1.txt
#  Hello {{ name }},
#   Welcome to DevOps Training

# output of cat /tmp/h2.txt
#  Hello John,
#   Welcome to DevOps Training
